# Generated by Django 5.2.5 on 2025-08-27 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Course code must be capital letters and numbers only.', regex='^[A-Z0-9]+$')]),
        ),
    ]
